version: '3'

services:
  receive:
    build:
      context: .
      dockerfile: receive.dockerfile
    ports:
      - "3000:3000"
    networks:
      - backend

  send:
    build:
      context: .
      dockerfile: send.dockerfile
    depends_on:
      - receive
    networks:
      - backend

networks:
  backend:
    driver: bridge
